spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: DEBUG
    com.sssms: DEBUG

springdoc:
  swagger-ui:
    enabled: true
